POST http://localhost:5000/v1/members
Content-Type: application/json

{
  "id": "test",
  "password": "test1234"
}

###
POST http://localhost:5000/v1/members/login
Content-Type: application/json

{
  "id": "test",
  "password": "test1234"
}

###
POST http://localhost:5000/v1/token/refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJrYWthb3BheSIsImV4cCI6MTU3NzM0OTI0NCwiaWF0IjoxNTc3MzQ3NDQ0LCJtZW1iZXJJZCI6InRlc3QifQ.R18KIq6gDr2ZrFvb6JFMEJQtH6liUnH0YhSNF1aZmcI

###
GET http://localhost:5000/v1/supports/rate
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJrYWthb3BheSIsImV4cCI6MTU3NzM0OTI0NCwiaWF0IjoxNTc3MzQ3NDQ0LCJtZW1iZXJJZCI6InRlc3QifQ.R18KIq6gDr2ZrFvb6JFMEJQtH6liUnH0YhSNF1aZmcI






###
GET localhost:5000/v1/supports/limit?size=3
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJrYWthb3BheSIsImV4cCI6MTU3NzM0OTI0NCwiaWF0IjoxNTc3MzQ3NDQ0LCJtZW1iZXJJZCI6InRlc3QifQ.R18KIq6gDr2ZrFvb6JFMEJQtH6liUnH0YhSNF1aZmcI



###
PUT localhost:5000/v1/supports
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJrYWthb3BheSIsImV4cCI6MTU3NzM1MDM2MywiaWF0IjoxNTc3MzQ4NTYzLCJtZW1iZXJJZCI6InRlc3QifQ.jyuJ0tVRB5gAXSpRdKxBmd9235CnRazHfv8GqHJmVtM

{
  "region": "강릉시",
  "target": "강릉시 소재 중소기업으로서 강릉시장이 추천한 자111111",
  "usage": "운전",
  "limit": "0",
  "maximumRate": "5.00",
  "minimumRate": "3.00",
  "institute": "강릉시",
  "mgmt": "강릉지점",
  "reception": "강릉시 소재 영업점"
}

###
GET localhost:5000/v1/supports?region=강릉시
Accept: application/json

###
POST localhost:5000/v1/supports
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJrYWthb3BheSIsImV4cCI6MTU3NzM1MDM2MywiaWF0IjoxNTc3MzQ4NTYzLCJtZW1iZXJJZCI6InRlc3QifQ.jyuJ0tVRB5gAXSpRdKxBmd9235CnRazHfv8GqHJmVtM

{
  "region": "강릉시",
  "target": "이성호가 추천한 자",
  "usage": "운전",
  "limit": "0",
  "maximumRate": "3.00",
  "minimumRate": "3.00",
  "institute": "강릉시",
  "mgmt": "강릉지점",
  "reception": "강릉시 소재 영업점"
}

###
